apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: flask
  name: python-app-dc
spec:
  replicas: 2
  selector:
    app: flask
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - image: python-app:latest
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - app
      from:
        kind: ImageStreamTag
        name: python-app:latest
    type: ImageChange
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
  labels:
    app: flask
spec:
  ports:
  - port: 80
    targetPort: 5000    
    protocol: TCP
    name: flask
  selector:
    app: flask
  type: LoadBalancer
