apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: appdeploy
        image: image-registry.openshift-image-registry.svc:5000/openshift/python-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
  labels:
    app: flask
spec:
  ports:
  - port: 80
    targetPort: 5000    
    protocol: TCP
    name: flask
  selector:
    app: flask
  type: LoadBalancer
