apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: python-app
  name: python-app
spec:
  source:
    type: Git
    git:
      ref: main
      uri: https://github.com/sriram1103/ocp_build.git
  strategy:
    type: Docker
    dockerStrategy:
  output:
    to:
      kind: ImageStreamTag
      name: python-app:latest
  triggers:
  - type: ConfigChange
  - imageChange:
      type: ImageChange
